//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddlewareApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/", ConfigurationName="ServiceReference1.ReceptionEndPoint")]
    public interface ReceptionEndPoint {
        
        // CODEGEN : Le paramètre 'message' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/receptionOperationRequ" +
            "est", ReplyAction="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/receptionOperationResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(receptionOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(receptionOperation))]
        MiddlewareApp.ServiceReference1.receptionOperationResponse1 receptionOperation(MiddlewareApp.ServiceReference1.receptionOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/receptionOperationRequ" +
            "est", ReplyAction="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/receptionOperationResp" +
            "onse")]
        System.Threading.Tasks.Task<MiddlewareApp.ServiceReference1.receptionOperationResponse1> receptionOperationAsync(MiddlewareApp.ServiceReference1.receptionOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/")]
    public partial class messageSOAPModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appVersionField;
        
        private object[] dataField;
        
        private string infoField;
        
        private string operationNameField;
        
        private string operationVersionField;
        
        private bool statusOpField;
        
        private bool statusOpFieldSpecified;
        
        private string tokenAppField;
        
        private string tokenUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
                this.RaisePropertyChanged("appVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string operationName {
            get {
                return this.operationNameField;
            }
            set {
                this.operationNameField = value;
                this.RaisePropertyChanged("operationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string operationVersion {
            get {
                return this.operationVersionField;
            }
            set {
                this.operationVersionField = value;
                this.RaisePropertyChanged("operationVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool statusOp {
            get {
                return this.statusOpField;
            }
            set {
                this.statusOpField = value;
                this.RaisePropertyChanged("statusOp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusOpSpecified {
            get {
                return this.statusOpFieldSpecified;
            }
            set {
                this.statusOpFieldSpecified = value;
                this.RaisePropertyChanged("statusOpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tokenApp {
            get {
                return this.tokenAppField;
            }
            set {
                this.tokenAppField = value;
                this.RaisePropertyChanged("tokenApp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tokenUser {
            get {
                return this.tokenUserField;
            }
            set {
                this.tokenUserField = value;
                this.RaisePropertyChanged("tokenUser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/")]
    public partial class receptionOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/")]
    public partial class receptionOperation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageSOAPModel messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public messageSOAPModel message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receptionOperation", WrapperNamespace="http://facade.ejb_jee7.reception.dev.com/", IsWrapped=true)]
    public partial class receptionOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MiddlewareApp.ServiceReference1.messageSOAPModel message;
        
        public receptionOperationRequest() {
        }
        
        public receptionOperationRequest(MiddlewareApp.ServiceReference1.messageSOAPModel message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receptionOperationResponse", WrapperNamespace="http://facade.ejb_jee7.reception.dev.com/", IsWrapped=true)]
    public partial class receptionOperationResponse1 {
        
        public receptionOperationResponse1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptionEndPointChannel : MiddlewareApp.ServiceReference1.ReceptionEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptionEndPointClient : System.ServiceModel.ClientBase<MiddlewareApp.ServiceReference1.ReceptionEndPoint>, MiddlewareApp.ServiceReference1.ReceptionEndPoint {
        
        public ReceptionEndPointClient() {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareApp.ServiceReference1.receptionOperationResponse1 MiddlewareApp.ServiceReference1.ReceptionEndPoint.receptionOperation(MiddlewareApp.ServiceReference1.receptionOperationRequest request) {
            return base.Channel.receptionOperation(request);
        }
        
        public void receptionOperation(MiddlewareApp.ServiceReference1.messageSOAPModel message) {
            MiddlewareApp.ServiceReference1.receptionOperationRequest inValue = new MiddlewareApp.ServiceReference1.receptionOperationRequest();
            inValue.message = message;
            MiddlewareApp.ServiceReference1.receptionOperationResponse1 retVal = ((MiddlewareApp.ServiceReference1.ReceptionEndPoint)(this)).receptionOperation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareApp.ServiceReference1.receptionOperationResponse1> MiddlewareApp.ServiceReference1.ReceptionEndPoint.receptionOperationAsync(MiddlewareApp.ServiceReference1.receptionOperationRequest request) {
            return base.Channel.receptionOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareApp.ServiceReference1.receptionOperationResponse1> receptionOperationAsync(MiddlewareApp.ServiceReference1.messageSOAPModel message) {
            MiddlewareApp.ServiceReference1.receptionOperationRequest inValue = new MiddlewareApp.ServiceReference1.receptionOperationRequest();
            inValue.message = message;
            return ((MiddlewareApp.ServiceReference1.ReceptionEndPoint)(this)).receptionOperationAsync(inValue);
        }
    }
}
