//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddlewareApp.ReferenceReceptionJEE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.ejb_jee7.reception.dev.com/", ConfigurationName="ReferenceReceptionJEE.ReceptionEndPoint")]
    public interface ReceptionEndPoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément decipheredText de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/createReceptionOperati" +
            "onRequest", ReplyAction="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/createReceptionOperati" +
            "onResponse")]
        MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse createReceptionOperation(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/createReceptionOperati" +
            "onRequest", ReplyAction="http://facade.ejb_jee7.reception.dev.com/ReceptionEndPoint/createReceptionOperati" +
            "onResponse")]
        System.Threading.Tasks.Task<MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse> createReceptionOperationAsync(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createReceptionOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createReceptionOperation", Namespace="http://facade.ejb_jee7.reception.dev.com/", Order=0)]
        public MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequestBody Body;
        
        public createReceptionOperationRequest() {
        }
        
        public createReceptionOperationRequest(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createReceptionOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decipheredText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usedKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        public createReceptionOperationRequestBody() {
        }
        
        public createReceptionOperationRequestBody(string decipheredText, string usedKey, string fileName) {
            this.decipheredText = decipheredText;
            this.usedKey = usedKey;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createReceptionOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createReceptionOperationResponse", Namespace="http://facade.ejb_jee7.reception.dev.com/", Order=0)]
        public MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponseBody Body;
        
        public createReceptionOperationResponse() {
        }
        
        public createReceptionOperationResponse(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createReceptionOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool acceptedReception;
        
        public createReceptionOperationResponseBody() {
        }
        
        public createReceptionOperationResponseBody(bool acceptedReception) {
            this.acceptedReception = acceptedReception;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptionEndPointChannel : MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptionEndPointClient : System.ServiceModel.ClientBase<MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint>, MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint {
        
        public ReceptionEndPointClient() {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptionEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint.createReceptionOperation(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest request) {
            return base.Channel.createReceptionOperation(request);
        }
        
        public bool createReceptionOperation(string decipheredText, string usedKey, string fileName) {
            MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest inValue = new MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest();
            inValue.Body = new MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequestBody();
            inValue.Body.decipheredText = decipheredText;
            inValue.Body.usedKey = usedKey;
            inValue.Body.fileName = fileName;
            MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse retVal = ((MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint)(this)).createReceptionOperation(inValue);
            return retVal.Body.acceptedReception;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse> MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint.createReceptionOperationAsync(MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest request) {
            return base.Channel.createReceptionOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationResponse> createReceptionOperationAsync(string decipheredText, string usedKey, string fileName) {
            MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest inValue = new MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequest();
            inValue.Body = new MiddlewareApp.ReferenceReceptionJEE.createReceptionOperationRequestBody();
            inValue.Body.decipheredText = decipheredText;
            inValue.Body.usedKey = usedKey;
            inValue.Body.fileName = fileName;
            return ((MiddlewareApp.ReferenceReceptionJEE.ReceptionEndPoint)(this)).createReceptionOperationAsync(inValue);
        }
    }
}
