/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.traitement.ejb_jee7.database;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author loicf
 */
//mark it entity using Entity annotation 
//map table name using Table annotation
@Entity
@Table(name="books")
public class Dictionary implements Serializable {
    
    private int id;
    private String word;

    public Dictionary() {        
    }

    public Dictionary(int id, String word) {
        this.id = id;
        this.word = word;
    }
    
    
    //mark id as primary key with autogenerated value
    //map database column id with id field
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="ID")
    public int getId() {
       return id;
    }

    @Column(name="WORD")
    public String getWord() {
        return word;
    }
}
